"""init tables

Revision ID: 065caa282e3a
Revises: 
Create Date: 2026-04-28 12:59:06.524353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065caa282e3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('pm', 'ur', 'ixd', 'dev', 'qa', 'admin', name='userrole'), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('prd_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('template_type', sa.Enum('agile', 'standard', 'detailed', name='templatetype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'published', 'locked', name='prdstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_story', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('insight', 'feedback', 'internal', 'competitor', name='requirementsource'), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'in_dev', 'done', name='requirementstatus'), nullable=False),
    sa.Column('rice_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planning', 'active', 'completed', name='projectstatus'), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('interviewee', sa.String(length=128), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentiment'), nullable=True),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prd_requirements',
    sa.Column('prd_id', sa.BigInteger(), nullable=False),
    sa.Column('requirement_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['prd_id'], ['prd_documents.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('prd_id', 'requirement_id')
    )
    op.create_table('prd_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prd_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prd_id'], ['prd_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prototypes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prd_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('generation_path', sa.Enum('agent', 'mcp', 'local', name='generationpath'), nullable=False),
    sa.Column('status', sa.Enum('generating', 'preview', 'exported', name='prototypestatus'), nullable=False),
    sa.Column('sitemap_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prd_id'], ['prd_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insight_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_type', sa.Enum('feature', 'experience', 'bug', 'painpoint', name='tagtype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('requirement_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prototype_pages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prototype_id', sa.BigInteger(), nullable=False),
    sa.Column('page_name', sa.String(length=128), nullable=False),
    sa.Column('route_path', sa.String(length=256), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('generating', 'done', 'error', name='pagestatus'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prototype_id'], ['prototypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prototype_pages')
    op.drop_table('insight_tags')
    op.drop_table('prototypes')
    op.drop_table('prd_versions')
    op.drop_table('prd_requirements')
    op.drop_table('interviews')
    op.drop_table('research_projects')
    op.drop_table('requirements')
    op.drop_table('prd_documents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
