"""add_prototype_preview_url_and_notes

Revision ID: 957bce92feca
Revises: d75b031c8930
Create Date: 2026-04-28 14:18:40.198235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957bce92feca'
down_revision: Union[str, None] = 'd75b031c8930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prototype_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prototype_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.Enum('meeting', 'annotation', name='notetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prototype_id'], ['prototypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prototypes', sa.Column('preview_url', sa.String(length=512), nullable=True, comment='本地项目预览地址'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prototypes', 'preview_url')
    op.drop_table('prototype_notes')
    # ### end Alembic commands ###
