"""add_project_techdoc_customerdoc_tables

Revision ID: d75b031c8930
Revises: 065caa282e3a
Create Date: 2026-04-28 13:20:40.177103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd75b031c8930'
down_revision: Union[str, None] = '065caa282e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True, comment='项目编号'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True, comment='客户名称'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='active/archived'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('customer_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='docdirection'), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False, comment='requirement/material/deliverable/meeting/contract'),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', name='docstatus'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('prd_id', sa.BigInteger(), nullable=True),
    sa.Column('doc_type', sa.String(length=32), nullable=False, comment='solution/api/database/deployment'),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', name='docstatus'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prd_id'], ['prd_documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prd_documents', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.add_column('prd_documents', sa.Column('section_background', sa.Text(), nullable=True))
    op.add_column('prd_documents', sa.Column('section_goals', sa.Text(), nullable=True))
    op.add_column('prd_documents', sa.Column('section_users', sa.Text(), nullable=True))
    op.add_column('prd_documents', sa.Column('section_features', sa.Text(), nullable=True))
    op.add_column('prd_documents', sa.Column('section_flow', sa.Text(), nullable=True))
    op.add_column('prd_documents', sa.Column('section_acceptance', sa.Text(), nullable=True))
    op.add_column('prd_documents', sa.Column('section_nonfunc', sa.Text(), nullable=True))
    op.alter_column('prd_documents', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Markdown 全文',
               existing_nullable=True)
    op.create_foreign_key(None, 'prd_documents', 'projects', ['project_id'], ['id'])
    op.add_column('prd_versions', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'prd_versions', 'users', ['created_by'], ['id'])
    op.add_column('requirements', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'requirements', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.drop_column('requirements', 'project_id')
    op.drop_constraint(None, 'prd_versions', type_='foreignkey')
    op.drop_column('prd_versions', 'created_by')
    op.drop_constraint(None, 'prd_documents', type_='foreignkey')
    op.alter_column('prd_documents', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Markdown 全文',
               existing_nullable=True)
    op.drop_column('prd_documents', 'section_nonfunc')
    op.drop_column('prd_documents', 'section_acceptance')
    op.drop_column('prd_documents', 'section_flow')
    op.drop_column('prd_documents', 'section_features')
    op.drop_column('prd_documents', 'section_users')
    op.drop_column('prd_documents', 'section_goals')
    op.drop_column('prd_documents', 'section_background')
    op.drop_column('prd_documents', 'project_id')
    op.drop_table('technical_documents')
    op.drop_table('customer_documents')
    op.drop_table('projects')
    # ### end Alembic commands ###
